import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          <li>
            <Link href="/test/foo">foo</Link>
          </li>
          <li>
            <Link href="/test/bar">bar</Link>
          </li>
          <li>
            <Link href="/test/baz">baz</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
